export const INDONESIAN_TO_JAVANESE: Record<string, string> = {
  'Kejadian': 'Purwaning Dumadi',
  'Keluaran': 'Pangentasan',
  'Imamat': 'Kaimaman',
  'Bilangan': 'Wilangan',
  'Ulangan': 'Pangandharing Toret',
  'Yosua': 'Yusak',
  'Hakim-hakim': 'Para Hakim',
  'Rut': 'Rut',
  '1 Samuel': '1 Samuel',
  '2 Samuel': '2 Samuel',
  '1 Raja-raja': '1 Para Raja',
  '2 Raja-raja': '2 Para Raja',
  '1 Tawarikh': '1 Babad',
  '2 Tawarikh': '2 Babad',
  'Ezra': 'Ezra',
  'Nehemia': 'Nehemya',
  'Ester': 'Ester',
  'Ayub': 'Ayub',
  'Mazmur': 'Jabur',
  'Amsal': 'Wulang Bebasan',
  'Pengkhotbah': 'Kohelet',
  'Kidung Agung': 'Musthikaning Kidung',
  'Yesaya': 'Yesaya',
  'Yeremia': 'Yeremia',
  'Ratapan': 'Kidung Pangadhuh',
  'Yehezkiel': 'Yeheskiel',
  'Daniel': 'Dhaniel',
  'Hosea': 'Hosea',
  'Yoel': 'Yoel',
  'Amos': 'Amos',
  'Obaja': 'Obaja',
  'Yunus': 'Yunus',
  'Mikha': 'Mikha',
  'Nahum': 'Nahum',
  'Habakuk': 'Habakuk',
  'Zefanya': 'Zefanya',
  'Hagai': 'Hagai',
  'Zakharia': 'Zakharia',
  'Maleakhi': 'Maleakhi',
  'Matius': 'Mateus',
  'Markus': 'Markus',
  'Lukas': 'Lukas',
  'Yohanes': 'Yokanan',
  'Kisah Para Rasul': 'Lelakone Para Rasul',
  'Roma': 'Rum',
  '1 Korintus': '1 Korinta',
  '2 Korintus': '2 Korinta',
  'Galatia': 'Galati',
  'Efesus': 'Efesus',
  'Filipi': 'Filipi',
  'Kolose': 'Kolose',
  '1 Tesalonika': '1 Tesalonika',
  '2 Tesalonika': '2 Tesalonika',
  '1 Timotius': '1 Timoteus',
  '2 Timotius': '2 Timoteus',
  'Titus': 'Titus',
  'Filemon': 'Filemon',
  'Ibrani': 'Ibrani',
  'Yakobus': 'Yakobus',
  '1 Petrus': '1 Petrus',
  '2 Petrus': '2 Petrus',
  '1 Yohanes': '1 Yokanan',
  '2 Yohanes': '2 Yokanan',
  '3 Yohanes': '3 Yokanan',
  'Yudas': 'Yudas',
  'Wahyu': 'Wahyu',
};
